### ISSUE TITLE
incompatible values of positive_count

### ISSUE THREAD

**Issue by Jou1721** [Ekim-Yurtsever/DeepTL-Lane-Change-Classification#13]
I don't want to bother you but I got this error. It happens when I run sample_training_maskRCNN_lstm.py
Traceback (most recent call last):
  File "D:/pythonProject/DeepTL-Lane-Change-Classification/test/mask_rcnn/sample_training_maskRCNN_lstm.py", line 15, in <module>
    masked_image_extraction.save_masked_images()
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\detect_objects.py", line 42, in save_masked_images
    model = modellib.MaskRCNN(mode="training", model_dir=MODEL_DIR, config=config)
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 1737, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 1877, in build
    target_rois, input_gt_class_ids, gt_boxes, input_gt_masks])
  File "D:\anaconda3\envs\myenv\lib\site-packages\keras\engine\base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 638, in `call`
    self.config.IMAGES_PER_GPU, names=names)
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\utils.py", line 673, in batch_slice
    output_slice = graph_fn(*inputs_slice)
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 637, in <lambda>
    w, x, y, z, self.config),
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 533, in detection_targets_graph
    negative_count = int((positive_count / config.ROI_POSITIVE_RATIO) - positive_count)
TypeError: unsupported operand type(s) for /: 'Tensor' and 'float'

>  positive_count = int(config.TRAIN_ROIS_PER_IMAGE *config.ROI_POSITIVE_RATIO)
positive_count = tf.shape(positive_indices)[0]

    negative_count = int((positive_count / config.ROI_POSITIVE_RATIO) - positive_count)

What is the true value of positive_count? The prediction model works well, I just can't start training.

**Comment by Jou1721** [comment]
The prediction model works well

> I don't want to bother you but I got this error. It happens when I run sample_training_maskRCNN_lstm.py
> Traceback (most recent call last):
> File "D:/pythonProject/DeepTL-Lane-Change-Classification/test/mask_rcnn/sample_training_maskRCNN_lstm.py", line 15, in
> masked_image_extraction.save_masked_images()
> File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\detect_objects.py", line 42, in save_masked_images
> model = modellib.MaskRCNN(mode="training", model_dir=MODEL_DIR, config=config)
> File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 1737, in **init**
> self.keras_model = self.build(mode=mode, config=config)
> File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 1877, in build
> target_rois, input_gt_class_ids, gt_boxes, input_gt_masks])
> File "D:\anaconda3\envs\myenv\lib\site-packages\keras\engine\base_layer.py", line 460, in **call**
> output = self.call(inputs, **kwargs)
> File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 638, in `call`
> self.config.IMAGES_PER_GPU, names=names)
> File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\utils.py", line 673, in batch_slice
> output_slice = graph_fn(*inputs_slice)
> File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 637, in
> w, x, y, z, self.config),
> File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 533, in detection_targets_graph
> negative_count = int((positive_count / config.ROI_POSITIVE_RATIO) - positive_count)
> TypeError: unsupported operand type(s) for /: 'Tensor' and 'float'
> 
> > positive_count = tf.shape(positive_indices)[0]
> 
> ```
> negative_count = int((positive_count / config.ROI_POSITIVE_RATIO) - positive_count)
> ```
> 
> positive_count is a tensor and has to be a tensor, while config.ROI_POSITIVE_RATIO is a float number. Is there any way to convert a tensor to a float number?

The prediction model works well, I just can't start training.

**Comment by Jou1721** [comment]
I set positive_count = int(config.TRAIN_ROIS_PER_IMAGE *config.ROI_POSITIVE_RATIO) and the training starts. Then I got a problem like this:
Traceback (most recent call last):
  File "D:/pythonProject/DeepTL-Lane-Change-Classification/test/mask_rcnn/sample_training_maskRCNN_lstm.py", line 15, in <module>
    masked_image_extraction.save_masked_images()
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\detect_objects.py", line 77, in save_masked_images
    results = model.detect([img], verbose=1)
  File "D:\pythonProject\DeepTL-Lane-Change-Classification\test\mask_rcnn\model.py", line 2316, in detect
    assert self.mode == "inference", "Create model in inference mode."
AssertionError: Create model in inference mode.
I have already selected training mode in detect_objects.py and cleared all the cache. Is there any more parameters need configuring?

**Comment by Jou1721** [comment]
> # Requires TensorFlow 1.3+ and Keras 2.0.8+.
model.py has a requirement like this. It seems not to be a Tensorflow version issue.

**Comment by Jou1721** [comment]
I run the training code in another folder then the problem is gone. However, I got a new one and I will start a new issue.
